env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.css', '.scss']
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {}
parser: babel-eslint
