AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'build_cache/**/*'
    - '**/*.haml'
    - 'vendor/bundle/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 150

Metrics/PerceivedComplexity:
  Max: 10

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/AsciiComments:
  Enabled: false
