# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 808a42a7cbb591143da3532d4391069f4f6df57797d98769427d27a3e0704eb770c609fa26031b88021906d3db3fe8484933b13fc95db1081b6640e038527414

test:
  secret_key_base: 68ece7b542fc62c85dd04cf8c19186fbc04e66a346578e59b46d2e0e5c79b6dab95a61e93f03ec67fbdbbc78c39c7604817b7e54039d6425b5a099b1b844ab37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
